name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8.8'
    - name: Install the library
      run: |
        make linux
        make build
    - name: Run tests
      run: |
        nbdev_test_nbs
